DECLARE MyCursor CURSOR SCROLL
FOR
    SELECT *
    FROM Ученики

OPEN MyCursor

FETCH ABSOLUTE 5 FROM MyCursor
FETCH PRIOR FROM MyCursor
FETCH ABSOLUTE -4 FROM MyCursor
FETCH NEXT FROM MyCursor
FETCH ABSOLUTE 1 FROM MyCursor

CLOSE MyCursor

DEALLOCATE MyCursor