DECLARE MyCursor CURSOR SCROLL
FOR
    SELECT *
    FROm Ученики

OPEN MyCursor

FETCH ABSOLUTE -1 FROM MyCursor
FETCH RELATIVE -6 FROM MyCursor
FETCH RELATIVE 4 FROM MyCursor

CLOSE MyCursor

DEALLOCATE MyCursor