DECLARE MyCursor CURSOR SCROLL
FOR
SELECT *
FROM
Ученики
OPEN MyCursor
FETCH ABSOLUTE 1 FROM MyCursor
WHILE @@FETCH_STATUS = 0
BEGIN
    FETCH RELATIVE 2 FROM MyCursor
END
CLOSE MyCursor
DEALLOCATE MyCursor
